### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by rmndrs89** [marcocaruso/mimu_optical_dataset_caruso_sassari#1]
Hi Marco,

I do not find the link to the files. Did you upload these to GitHub, or have you used any other platform?

Best,
Robbin

**Comment by marcocaruso** [comment]
Hi Robbin,

thanks for pointing this out. If you go here, is it possible to download it? https://github.com/marcocaruso/mimu_optical_dataset_caruso_sassari/releases/tag/v5.0

Otherwise the same dataset is available here:
https://it.mathworks.com/matlabcentral/fileexchange/91200-mimu_optical_dataset_caruso_sassari

**Comment by rmndrs89** [comment]
Aha, yes, now I know where to find it, thanks! :dancers:
